### ISSUE TITLE
Imports does not work in ubuntu 18.04 LTS. 

### ISSUE THREAD

**Issue by Sktbanerjee1** [tsileo/dirtools#7]
After installing the package from pypi, while importing throws syntax error at line 333. 
Is a new version on the pipeline?

**Comment by kelvins** [comment]
It is related to issue https://github.com/tsileo/dirtools/issues/6.

**Comment by otapi** [comment]
Maybe you are still interested, I made a fork and published the latest with Python3 support + some bugfixes to pypi as dirtools2.
You can install it with `pip install dirtools2`.
For more, see https://github.com/otapi/dirtools2
